name: "SuperAnnotate Custom Action Sync"
description: "Automatically sync custom actions to SuperAnnotate using the Zimmer API."

inputs:
  token:
    description: "SuperAnnotate API token"
    required: true
  actions_path:
    description: "Directory containing custom actions"
    required: false
    default: "actions"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        pip install pyyaml requests

    - name: Run SuperAnnotate sync
      shell: bash
      run: |
        python scripts/sync.py
      env:
        PLATFORM_TOKEN: ${{ inputs.token }}
        ACTIONS_DIR: ${{ inputs.actions_path }}

branding:
  icon: upload-cloud
  color: blue

